"""Edit model Booking

Revision ID: 3d9895a95bc9
Revises: 8c6c6f3cecf4
Create Date: 2023-12-01 18:09:40.720131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9895a95bc9'
down_revision: Union[str, None] = '8c6c6f3cecf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
